### PR TITLE
Initialize bot and constants, add utils.

### PR DESCRIPTION
**Pull request by abhigyantrips**
This finishes up some of the tasks to be completed before we start working on cogs and other functions.

### CODE REVIEW

**Comment by abhigyantrips** [comment]
Changes made so far: 
- Added constants for colors and channels (the channels point to IDs in my test server, while this PR is still open).
- Made changes to poetry config (there was an old `mahebot` dir. reference blocking the workflow).
- Added utility commands, such as `ping`.

**Review by aghogwarts — COMMENTED** [review]
This is a nice edit to the basic configs done in the files. Furthermore we can add more stats to the bot as and when the database is added

**Comment by aghogwarts** [comment]
Why are we making it compatible for future message command implementation possibility

**Comment by abhigyantrips** [comment]
> Why are we making it compatible for future message command implementation possibility

It's always better to have alternatives to application commands, especially for moderation purposes. The bot's dependency on message commands can be discussed later.

**Comment by aghogwarts** [comment]
> > Why are we making it compatible for future message command implementation possibility
> 
> It's always better to have alternatives to application commands, especially for moderation purposes. The bot's dependency on message commands can be discussed later.

Ah okay fair 👍

**Review by dhzdhd — APPROVED** [review]
LGTM!

**Pull request merged**
